### ISSUE TITLE
AidType list is missing a new value

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/codelist-updater#69]
I'm not exactly sure where the scraper for AidType lives @markbrough - but it's currently out of synch with IATI /DAC:

 https://iatistandard.org/en/iati-standard/203/codelists/aidtype/

`
H06 | Refugees and asylum seekers in other provider countries | Costs incurred in other non-ODA eligible provider countries for basic assistance to asylum seekers and refugees from developing countries, up to 12 months. The host and origin country of refugees/asylum seekers shall be specified in one of the descriptive fields of the CRS (fields 14 or 19).`

...is missing from https://codelists.codeforiati.org/AidType/

(originally via https://github.com/OpenDataServices/cove/issues/1386)

**Comment by markbrough** [comment]
This is now fixed! Via https://github.com/codeforIATI/IATI-Codelists-NonEmbedded/commit/abbf4f71672b3b54ea7608f64958c6259fd660f6
